POST http://fervent-kilby-2a6af4.netlify.app:4000/app/signup
Content-Type: application/json

{
    "firstName":"eeeeeeee",
    "lastName":"Terok123",
    "email":"mg.terok123s@gmail.com",
    "phone":"085696769836",
    "password":"123123"
}