POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName":"asdasdas",
    "lastName":"Terok123",
    "email":"mg.terok123@gmail.com",
    "phone":"085696769836",
    "password":"123123"
}