POST http://young-wildwood-72286.herokuapp.com/app/signup
Content-Type: application/json

{
    "firstName":"eeeeeeee",
    "lastName":"Terok123",
    "email":"mg.terok123s@gmail.com",
    "phone":"085696769836",
    "password":"123123"
}